### ISSUE TITLE
Failures to run `buf lint` due to non-lint errors don't fail the action

### ISSUE THREAD

**Issue by carols10cents** [bufbuild/buf-lint-action#120]
I have a reproducing repo at https://github.com/carols10cents/buf-repro, specifically in https://github.com/carols10cents/buf-repro/pull/3.

This applies to the `buf-breaking-action` too, but I arbitrarily picked this repo to file the issue in. Let me know if you'd like one over there too.

The `.github/workflows/buf-lint.yml` contains this (which also runs `buf breaking`):

```yml
name: "Protobuf Lint"
on:
   pull_request:
     types:
       - labeled
       - opened
       - reopened
       - synchronize
jobs:
  lint-protos:
    runs-on: ubuntu-latest
    name: Buf lint
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'incompatible protobuf') }}
        with:
          fetch-depth: '100'
          submodules: true
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'incompatible protobuf') }}
      # Run breaking change detection against the `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'incompatible protobuf') }}
        with:
          against: 'https://github.com/influxdata/influxdb_iox.git#branch=main'
      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'incompatible protobuf') }}

      # Be helpful if the lint fails
      - name: Lint failure! Read this :)
        if: ${{ failure() }}
        run: |
          echo "If you want to make changes forbidden by this lint, please"
          echo "coordinate with the IOx team, add the 'incompatible protobuf' label"
          echo "to the PR, and rerun this test"
```

The PR reverts a commit that fixed a previous issue with file imports; that is, it breaks again and I expected the action run to fail-- [but it passed](https://github.com/carols10cents/buf-repro/actions/runs/9292343005/job/25573031573?pr=3).

However, toggling open the logs for `buf-breaking-action` shows:

```
Run bufbuild/buf-breaking-action@v1
Failure: bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto: import "generated_types/protos/influxdata/iox/column_type/v1/type.proto": file does not exist
Failure: bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto: import "generated_types/protos/influxdata/iox/column_type/v1/type.proto": file does not exist
No breaking errors were found.
```

and toggling open the logs for `buf-lint-action` shows:

```
Run bufbuild/buf-lint-action@v1
Failure: bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto: import "generated_types/protos/influxdata/iox/column_type/v1/type.proto": file does not exist
Failure: bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto: import "generated_types/protos/influxdata/iox/column_type/v1/type.proto": file does not exist
No lint errors were found.
```

I expected these `Failure` messages to cause the job to fail, because the actions aren't able to actually check these files.
