### ISSUE TITLE
Lint fails in workflow if the buf.lock file is present

### ISSUE THREAD

**Issue by oliveiraethales** [bufbuild/buf-lint-action#13]
Hello buf team!

Found an interesting issue while setting up a repo with the lint action and when using the latest `buf` version [1.0.0-rc12](https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc12) where basically if the `buf.lock` file is committed and present, the lint fails with `Failure: branch is not main`. If the `buf.lock` file is not present, then linting proceeds as expected but this is of course not ideal since the lock file should be commited & pushed. The lock file was not manually modified and was generated by `buf mod update`.

![failure](https://user-images.githubusercontent.com/208830/154549000-99de6565-9a66-4570-93d8-b3507161efff.png)

Perhaps this is related to the removal of the `branch` field from `buf.lock` on 1.0.0-rc12?

Could you assist please? Thank you!

**Comment by doriable** [comment]
Hi @oliveiraethales, thanks for filing this issue! Yes, this is related to the removal of the `branch` field in the `buf.lock`, sorry for the inconvenience! I have a couple of questions for you regarding your workflows and setups, so I can help reproduce and debug:

- Just to make sure, for `buf-lint-action`, you're using the same version (`v1.0.0-rc12`) across all your workflows? (e.g. locally, for updating dependencies, pushing code, etc.?)
- If yes to the former, are you able to run `buf lint` with the `buf.lock` present in the local setup with this `buf` version?

**Comment by oliveiraethales** [comment]
Hey @doriable, thanks for the super fast response (:

- Yes, `buf-lint-action` is `@v1`
- Yes, `buf lint` works ok locally!

This is the whole steps section of the PR workflow (this was based on buf GH action docs):

```
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main'
```

And this would be `buf.yaml`:
```
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

And this is `buf.lock`:

```
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    commit: 81f739c974504624a4ecca7b5a42ca33
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    commit: ff83506eb9cc4cf8972f49ce87e6ed3e
```

Output of `buf version` locally:
```
➜ buf --version
1.0.0-rc12
```
