### ISSUE TITLE
Is some special config needed to enable PR comments?

### ISSUE THREAD

**Issue by erikbern** [bufbuild/buf-lint-action#14]
Just tried setting this up on a private repo and I see the output in the Github Actions logs, but it's not posting anything to the PR.

My config:

```
  buf:
    name: Buf
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bufbuild/buf-setup-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bufbuild/buf-lint-action@v1
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

I might be doing something dumb but I didn't see anything obvious in the documentation (also looked at the source code of this action and still not sure what I'm doing wrong).

Thanks!!
