### ISSUE TITLE
action falsely throwing errors

### ISSUE THREAD

**Issue by ryan-z** [bufbuild/buf-lint-action#80]
Hello,

I added this action to a private repo and it runs and then fails with a few errors that I've since fixed locally. The linter is stuck on two issues:

1. The action is not properly using the `enum_zero_value_suffix` that I overrode in buf.yaml
The buf.yaml is in the project root, and looks like
```
version: v1
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/protoc-gen-swagger
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
  enum_zero_value_suffix: _NONE
```

I see error annotations for each enum in the proto, such as `Enum zero value name "ERROR_CODE_NONE" should be suffixed with "_UNSPECIFIED".`

2. My foo.proto package is named like `foo.v1` and I have the directory structure as `<root>/foo/v1/foo.proto`
So I specify in the github action yaml like so:
```
      - name: Lint Protos
        uses: bufbuild/buf-lint-action@v1
        with:
          input: 'foo'
```
But the linter still errors, claiming that the package isn't in a foo/v1 directory when it actually is:
`Files with package "foo.v1" must be within a directory "foo/v1" relative to root but were in directory "v1".`

One more detail: I was missing a version in the package name initially, but I have since changed the package name to include it. Not sure if that matters or not.
